minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@oxc-resolver/binding-darwin-arm64@4.2.0'
  - '@oxc-resolver/binding-darwin-x64@4.2.0'
  - '@oxc-resolver/binding-linux-arm64-gnu@4.2.0'
  - '@oxc-resolver/binding-linux-x64-gnu@4.2.0'
  - '@oxc-resolver/binding-win32-arm64-msvc@4.2.0'
  - '@oxc-resolver/binding-win32-x64-msvc@4.2.0'
  - '@swc/core@1.7.22'
  - chokidar@4.0.3
  - semver@6.3.1

shellEmulator: true
saveExact: true

packages:
  - packages/*
  - apps/*

overrides:
  '@nuxt/devtools': 3.4.2
  better-sqlite3: 13.0.3

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
