packages:
  - packages/*
  - apps/*
overrides:
  '@nuxt/devtools': 3.4.2
  better-sqlite3: 12.10.0
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
saveExact: true
